# Generated by Django 3.0.5 on 2020-05-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmtopo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vm_pg',
            old_name='temp_name',
            new_name='vm_name',
        ),
    ]
