# Generated by Django 3.0.5 on 2020-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
