# Generated by Django 3.0.5 on 2020-05-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0006_remove_clone_temp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='title',
        ),
    ]
