# Generated by Django 3.0.5 on 2020-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0007_remove_deploy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='deploy_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
