# Generated by Django 3.0.5 on 2020-05-17 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0008_deploy_deploy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='deploy_name',
        ),
        migrations.AddField(
            model_name='deploy',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
