# Generated by Django 3.0.5 on 2020-05-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0010_auto_20200517_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='title',
        ),
        migrations.AddField(
            model_name='deploy',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
