# Generated by Django 3.0.5 on 2020-05-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwtopo', '0011_auto_20200517_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='date_time',
        ),
    ]
